export const SAMPLE_MARKDOWN = [
  "# Direct Mode Demo",
  "",
  "This is a realistic assistant response for direct-mode formatting checks.",
  "It mixes **bold**, _italic_, `inline code`, links, code fences, and tables in one streamed reply.",
  "",
  "## Summary",
  "",
  "- Restored the final markdown flush so the last block is committed on idle.",
  "- Switched markdown scrollback commits back to top-level block boundaries.",
  "- Added footer-level regression coverage for split-footer rendering.",
  "",
  "## Status",
  "",
  "| Area | Before | After | Notes |",
  "| --- | --- | --- | --- |",
  "| Direct mode | Missing final rows | Stable | Final markdown block now flushes on idle |",
  "| Tables | Dropped in streaming mode | Visible | Block-based commits match the working OpenTUI demo |",
  "| Tests | Partial coverage | Broader coverage | Includes a footer-level split render capture |",
  "",
  "> This sample intentionally includes a wide table so you can spot wrapping and commit bugs quickly.",
  "",
  "```ts",
  "const result = { markdown: true, tables: 2, stable: true }",
  "```",
  "",
  "## Files",
  "",
  "| File | Change |",
  "| --- | --- |",
  "| `scrollback.surface.ts` | Align markdown commit logic with the split-footer demo |",
  "| `footer.ts` | Keep active surfaces across footer-height-only resizes |",
  "| `footer.test.ts` | Capture real split-footer markdown payloads during idle completion |",
  "",
  "Next step: run `/fmt table` if you want a tighter table-only sample.",
].join("\n")

export const SAMPLE_TABLE = [
  "# Table Sample",
  "",
  "| Kind | Example | Notes |",
  "| --- | --- | --- |",
  "| Pipe | `A\\|B` | Escaped pipes should stay in one cell |",
  "| Unicode | `漢字` | Wide characters should remain aligned |",
  "| Wrap | `LongTokenWithoutNaturalBreaks_1234567890` | Useful for width stress |",
  "| Status | done | Final row should still appear after idle |",
].join("\n")

export const MARKDOWN_PATTERNS = {
  "md-code": [
    "# Interleaved Code",
    "",
    "Start with a short conclusion before any code appears.",
    "",
    "```ts",
    "export function parse(input: string) {",
    "  return input.trim().split(/\\s+/)",
    "}",
    "```",
    "",
    "Then continue with prose immediately after the code block. This should not inherit code styling or indentation.",
    "",
    "```tsx",
    "<Show when={props.enabled}>",
    "  <markdown content={props.text} streaming />",
    "</Show>",
    "```",
    "",
    "Final paragraph after a second fence with `inline code`, **bold text**, and _emphasis_ mixed together.",
  ].join("\n"),
  "md-fence": [
    "# Fence Boundaries",
    "",
    "The renderer should recover cleanly around multiple fences and nearby paragraphs.",
    "",
    "```bash",
    "bun run test -- --grep markdown",
    "```",
    "Text directly after a fence.",
    "```json",
    "{",
    '  "status": "ok",',
    '  "items": ["one", "two"]',
    "}",
    "```",
    "Trailing paragraph after JSON. The next fence intentionally has no language.",
    "```",
    "plain fenced text",
    "with multiple lines",
    "```",
  ].join("\n"),
  "md-list": [
    "# Lists With Code",
    "",
    "1. First ordered item with `inline code`.",
    "2. Second ordered item before a nested list:",
    "   - Nested bullet with a long phrase that should wrap without swallowing the marker or changing indentation.",
    "   - Nested bullet before fenced code:",
    "",
    "     ```ts",
    "     const nested = true",
    "     ```",
    "",
    "3. Third ordered item after the nested fence.",
    "",
    "- Top-level bullet after ordered list.",
    "- Another bullet with a paragraph below.",
    "",
    "  Continuation paragraph should stay associated with the bullet without becoming code.",
  ].join("\n"),
  "md-table-code": [
    "# Tables And Code",
    "",
    "| Case | Input | Expected |",
    "| --- | --- | --- |",
    "| Inline code | `const x = 1` | stays inline |",
    "| Escaped pipe | `A\\|B` | one cell |",
    "| Long token | `LongTokenWithoutNaturalBreaks_1234567890_abcdefghijklmnopqrstuvwxyz` | wraps or scrolls predictably |",
    "",
    "A code block follows the table:",
    "",
    "```ts",
    "const rows = [",
    '  { case: "inline code", expected: "stays inline" },',
    '  { case: "escaped pipe", expected: "one cell" },',
    "]",
    "```",
    "",
    "And then another compact table:",
    "",
    "| A | B |",
    "| - | - |",
    "| done | yes |",
  ].join("\n"),
  "md-inline": [
    "# Inline Markdown",
    "",
    "This paragraph mixes [a normal link](https://opencode.ai), `https://example.com/code-link`, `inline code`, **strong**, _emphasis_, and ~~strikethrough~~.",
    "",
    "> Blockquote with `inline code` and [a link](https://example.com) should keep quote styling while wrapping.",
    "",
    "A horizontal rule follows.",
    "",
    "---",
    "",
    "After the rule, text should resume normal spacing.",
  ].join("\n"),
  "md-kitchen": [
    "# Markdown Kitchen Sink",
    "",
    "This combines headings, paragraphs, lists, blockquotes, tables, inline code, and multiple code fences.",
    "",
    "## Steps",
    "",
    "1. Read the response.",
    "2. Notice `inline code` before a block.",
    "",
    "```ts",
    "type Result = { ok: boolean; reason?: string }",
    "const result: Result = { ok: true }",
    "```",
    "",
    "3. Continue the list after the block.",
    "",
    "> Quoted note after the list. It should not merge into the previous item.",
    "",
    "| Feature | Stress |",
    "| --- | --- |",
    "| Markdown | prose/code/table interleave |",
    "| Renderer | wrapping and spacing |",
    "",
    "```diff",
    "- const renderer = oldMarkdown",
    "+ const renderer = experimentalMarkdown",
    "```",
    "",
    "Final paragraph with [docs](https://opencode.ai/docs) and `https://example.com/from-code`.",
  ].join("\n"),
} as const

export const MARKDOWN_PATTERN_KINDS = Object.keys(MARKDOWN_PATTERNS) as Array<keyof typeof MARKDOWN_PATTERNS>
